language: c
cache: ccache
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx

before_install:
  - date
  - make deps
  - make get

script: 'make test'

go:
  - 1.5
  - 1.8
